apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nginx-test-deployment
  namespace: argocd-nginx-test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argocd-nginx-test
    spec:
      containers:
        - ports:
            - containerPort: 80
          resources:
            limits:
              memory: 128Mi
              cpu: 150m
            requests:
              memory: 64Mi
              cpu: 100m
          name: argocd-nginx-test
          image: nginx:latest
          imagePullPolicy: Always
  selector:
    matchLabels:
      app: argocd-nginx-test